const int BOATSTRIGGERPIN 2
const int MYTHSTRIGGERPIN 3
const int FALCONSTRIGGERPIN 4
const int SANDTRIGGERPIN 5
const int BLOCKSTRIGGERPIN 6

const int BOATSDONEPIN 7
const int MYTHSDONEPIN 8
const int FALCONSDONEPIN 9
const int SANDDONEPIN 10
const int BLOCKSDONEPIN 11

const int WHICHHANDPIN 12
const int WHICHDIRECTION PIN 13
const int STEPPIN A0

const int HOURZEROPIN A1
const int MINZEROPIN A2

const int RTCGNDPIN 